<div class="padding-top"></div>
<div class="divider"></div>
<h5 class="padding-top">Do you have a question or is something missing?</h5>
<p class="padding-top" style="margin-bottom: 16px;">
   You can always create a new issue on <a href="https://github.com/thorinjs/docs" target="_blank">GitHub</a> or contact
   one of the core founders <a href="https://unloq.io" target="_blank">by chat</a>.
</p>
